# Generated by Django 4.1.6 on 2023-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointmentsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointmentsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
