# Generated by Django 4.1.6 on 2023-02-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='username',
        ),
    ]
